name: 4ce-py
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - jupyter
  - nb_conda
  - ipykernel
  - pandas
  - numpy
  - altair
  - ipywidgets
  - python-dateutil
  - altair_saver
  - vega_datasets
